name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp_zap_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Download OWASP ZAP
      - name: Download OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz
          tar -xzf ZAP_2.10.0_Linux.tar.gz

      # Step 3: Install Java (if required by OWASP ZAP)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 4: Run ZAP Spider and Active Scan
      - name: Run ZAP Spider and Active Scan
        run: |
          ./ZAP_2.10.0/zap.sh -cmd -quickurl https://your-php-website.com -quickprogress -quickout /zap/report.html -quickcmd cmd:quick-scan

      # Step 5: Save ZAP report as workflow artifact
      - name: Save ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /zap/report.html
