name: StackHawk Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: StackHawk Security Scan
        uses: stackhawk/action@v2
        with:
          api-key: ${{ secrets.SHAWK_TOKEN }}
          target-url: http://localhost/online-shopping-webvsite-in-php-master 
